#!/usr/bin/env bash

IPFTRACE_COMMAND=""
DOCKER_COMMAND=""
POSITIONAL_ARGS=0

if [ -z $IPFTRACE_DOCKER_IMAGE ]; then
  DOCKER_IMAGE="yutarohayakawa/ipftrace:latest"
else
  DOCKER_IMAGE=$IPFTRACE_DOCKER_IMAGE
fi

if [ -z $IPFTRACE_DEBUGFS_DIR ]; then
  DEBUGFS_DIR="/sys/kernel/debug"
else
  DEBUGFS_DIR=$IPFTRACE_DEBUGFS_DIR
fi

if [ -z $IPFTRACE_KERNEL_SOURCE_DIR ]; then
  KERNEL_SOURCE_DIR="/usr/src"
else
  KERNEL_SOURCE_DIR=$IPFTRACE_KERNEL_SOURCE_DIR
fi

if [ -z $IPFTRACE_KERNEL_MODULES_DIR ]; then
  KERNEL_MODULES_DIR="/lib/modules"
else
  KERNEL_MODULES_DIR=$IPFTRACE_KERNEL_MODULES_DIR
fi

DOCKER_COMMAND+="docker run --rm --privileged"
DOCKER_COMMAND+=" -v $DEBUGFS_DIR:/sys/kernel/debug"
DOCKER_COMMAND+=" -v $KERNEL_SOURCE_DIR:/usr/src"
DOCKER_COMMAND+=" -v $KERNEL_MODULES_DIR:/lib/modules"

while [[ $# -gt 0 ]]; do
  case $1 in
    -iv|--ipversion)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -s|--saddr)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -d|--daddr)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -p|--proto)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -sp|--sport)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -dp|--dport)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -r|--regex)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -l|--length)
      IPFTRACE_COMMAND+=" $1 $2"
      shift 2
      ;;
    -ls|--show)
      IPFTRACE_COMMAND+=" $1"
      shift
      ;;
    -m|--module)
      IPFTRACE_COMMAND+=" $1 /module.py"
      DOCKER_COMMAND+=" -v $(realpath $2):/module.py"
      shift 2
      ;;
    -*|--*)
      IPFTRACE_COMMAND+=" $1"
      shift
      ;;
    *)
      if [ $POSITIONAL_ARGS = 0 ]; then
        IPFTRACE_COMMAND+=" /manifest.yaml"
        DOCKER_COMMAND+=" -v $(realpath $1):/manifest.yaml"
      else
        IPFTRACE_COMMAND+=" $1"
      fi
      POSITIONAL_ARGS=$(( $POSITIONAL_ARGS + 1 ))
      shift
      ;;
  esac
done

$DOCKER_COMMAND $DOCKER_IMAGE $IPFTRACE_COMMAND
